version: "3"

volumes:
  mongodb_volume:

services:
  tg_scraper:
    build:
      context: .
      dockerfile: ./PKparser/Dockerfile
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - mongodb_service
    networks:
      - lognet

  mongodb_service:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_DATABASE: pk_db
    ports:
      - 27017:27017
    networks:
      - lognet

networks:
  lognet:
    driver: bridge